variable "audit_role_arn" {
 description = "The ARN of the IAM role attach the policy to"
 type = string
 default = "arn:aws:iam::429060775154:role/s1-cns-audit-2215028619070184314"
}
variable "audit_role_name" {
 description = "The name of IAM role attach the policy to"
 type = string
 default = "s1-cns-audit-2215028619070184314"
}
variable "root_ou_id" {
 description = "The name of IAM role attach the policy to"
 type = string
 default = "r-38w6"
}
variable "iam_path" {
 description = "The path for the IAM role to be created in AWS account."
 type = string
 default = "/"
}
variable "permission_boundary_arn" {
 description = "The ARN of the policy that is used to set the permissions boundary for the IAM role."
 type = string
 default = ""
}
variable "identifier" {
 description = "The unique identifier for the integration. This identifier is used to create unique resource names."
 type = string
 default = "2215028619070184314"
}
variable "enable_cloudtrail" {
 description = "Enable CloudTrail"
 type = string
 default = "Yes"
}
variable "marketplace_external_id" {
 description = "The external ID auto-generated by SentinelOne. Do not change this value."
 type = string
 default = "840ed2e1718aa53f389c95e9d0c5fdff9fb9518cc9d75c06f1482cb0ab5958ff"
}
variable "cloudtrail_bucket_name" {
 description = "The name of the S3 bucket to store CloudTrail logs."
 type = string
 default = "aws-cloudtrail-validation-logs-429060775154-78f3c786"
}
variable "cloudtrail_kms_arn" {
 description = "The ARN of the KMS key attached to the CloudTrail."
 type = string
 default = "arn:aws:kms:us-east-1:429060775154:key/54ec11dc-05a4-4980-9e00-67b7a6ca0d74"
}
variable "bucket_owner_account_id" {
 description = "The AWS account ID of the bucket owner."
 type = string
 default = "429060775154"
}
variable "is_organization_onboarding" {
 description = "Is the organization onboarding."
 type = string
 default = "No"
}
variable "existing_sns_topic_arn" {
 description = "The ARN of the existing SNS topic."
 type = string
 default = "arn:aws:sns:us-east-1:429060775154:aws-cloudtrail-validation-logs-429060775154-82244636"
}
variable "existing_sns_topic_account_id" {
 description = "The AWS account ID of the existing SNS topic."
 type = string
 default = "429060775154"
}
variable "audit_role_for_bucket_access" {
 description = "The ARN of the IAM role attach the policy to"
 type = string
 default = "arn:aws:iam::429060775154:role/s1-cns-audit-2215028619070184314"
}